name: Build Binaries
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-avr-toolchain mingw-w64-x86_64-freeglut
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mingw32-make build-simavr V=1
          mkdir simavr_installed
          mingw32-make install DESTDIR=$(pwd)/simavr_installed/
          mv simavr_installed/bin/simavr simavr_installed/bin/simavr.exe
          file simavr_installed/bin/*